### ISSUE TITLE
Docker mounts - lagre database og logger til fil.

### ISSUE THREAD

**Issue by heming-langrenn** [langrenn-sprint/result-service-gui#115]

**Comment by stigbd** [comment]
Oppretter nytt issue på å monitorere logger. Ref https://github.com/langrenn-sprint/deploy/issues/1

**Comment by stigbd** [comment]
Eg er usikker på korleis ein får lagra loggene til fil. Det krever litt meir innsats som eg må ta seinare.

Den andre delen av issuet, skrive database til permanent disk, går eg i gang med no.

**Comment by stigbd** [comment]
Då har eg
1. Dokumentert i deploy korleis monitorere logger i virtuel maskin i azure
2. Lagt til volume i mongodb i docker-compose.yml i deploy, slik ta mongodb blir skrive til ekstern disk (den virtuelle maskina sin disk i azure)

Det som evt gjenstår er å lage ein data disk i azure som ein kan skrive mongodb til. Dette virkar litt meir komplisert, og eg har ikkje fått oversikt over kva som skal til.

@heming-langrenn Kan du teste deploy og sjå om dette er tilfredsstilande?

**Comment by heming-h** [comment]
Yes, bra. Dette funker! Da kan vi klare å fange opp hva som skjer underveis hvis det blir behov for det!
