### ISSUE TITLE
Mulighet for å vise resultater i tilfeldig rekkefølge

### ISSUE THREAD

**Issue by heming-h** [langrenn-sprint/result-service-gui#178]
Typisk funksjon for kl 11 og 12 år.
Bør ha dette som en parameter på raceclass

**Comment by stigbd** [comment]
Er dette nye regler? Før skulle 11 år og oppover rangeres.

**Comment by heming-h** [comment]
Use case er: For 11 og 12 åringene er det premier til alle og løperne ropes opp i tilfeldig rekkefølge. Man ønsker å unngå at den som kom sist også blir lest opp sist. H14. mar. 2024 08:39 skrev "Stig B. Dørmænen" ***@***.***>:
Er dette nye regler? Før skulle 11 år og oppover rangeres.

**Comment by stigbd** [comment]
> Use case er: For 11 og 12 åringene er det premier til alle og løperne ropes opp i tilfeldig rekkefølge. Man ønsker å unngå at den som kom sist også blir lest opp sist. H14. mar. 2024 08:39 skrev "Stig B. Dørmænen" ***@***.***>: Er dette nye regler? Før skulle 11 år og oppover rangeres. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were assigned.Message ID: ***@***.***>

Forstår det med _opplesning_ i tilfeldig rekkefølge.

Men likevel er dette uklart for meg. Vi skal publisere resultatlister, men utan rangering for 11 og 12? Eller skal resultat-lista inneholde plassering (1.plass, 2.plass, etc), men vi skal ikkje sortere på plassering?

Relevant reglement er 317.2.2 i [rennreglementet](https://www.skiforbundet.no/globalassets/04-gren---medier/langrenn/regler-og-retningslinjer/2022-rennreglement-langrenn---godkjent.pdf).

**Comment by heming-h** [comment]
Ja. Vise i tilfelle rekkefølge er nok en mer presis beskrivelse. H14. mar. 2024 11:46 skrev "Stig B. Dørmænen" ***@***.***>:

Use case er: For 11 og 12 åringene er det premier til alle og løperne ropes opp i tilfeldig rekkefølge. Man ønsker å unngå at den som kom sist også blir lest opp sist. H14. mar. 2024 08:39 skrev "Stig B. Dørmænen" @.>: Er dette nye regler? Før skulle 11 år og oppover rangeres. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were assigned.Message ID: @.>

Forstår det med opplesning i tilfeldig rekkefølge.
Men likevel er dette uklart for meg. Vi skal publisere resultatlister, men utan rangering for 11 og 12? Eller skal resultat-lista inneholde plassering (1.plass, 2.plass, etc), men vi skal ikkje sortere på plassering?
Relevant reglement er 317.2.2 i rennreglementet.

**Comment by stigbd** [comment]
Bra oppklaring. Foreslår at vi introduserer, som du seier, nytt felt på raceclass-modellen, feks `results-in-ranking-order: bool = True` .
