### ISSUE TITLE
Må kunne flytte løper fra ett heat til eit anna underveis i rennet

### ISSUE THREAD

**Issue by stigbd** [langrenn-sprint/result-service-gui#32]
Typisk scenario: løper kommer for seint til start, får gå i ledig spor i etterfølgende heat.

Situasjonen no: ved forsøk på å registrere målpassering på løper i faktisk heat, får man feilmelding

Ønsket situasjon er antagelegvis: å flytte løper's start-entry til etterfølgende heat.

**Comment by heming-langrenn** [comment]
Foreslår å lage to funksjoner:
- Fjerne løper fra startliste
- Legge til løper i startliste.

Dette er en enklere løsning som bør kunne løse de fleste varianter av "flytte" use-cases.

**Comment by heming-langrenn** [comment]
Har laget funksjonalitet både for start og resultatlister - "Redigere resultater"
