### ISSUE TITLE
Må kunne holde igjen publisering av resultater

### ISSUE THREAD

**Issue by heming-langrenn** [langrenn-sprint/result-service-gui#34]
Gir mulighet for å styre når resultater blir tilgjengelige på nett og live-skjermer.

Dette krever at vi har en attributt i databasen som styrer om resultater skal vises. Den bør vel ligge på race? @stigbd - kommentarer?

**Comment by stigbd** [comment]
Eg hadde sett for meg at vi lagde en attribtutt på RaceResult, feks `status`, som kan ha tre verdier ved bruk av en enum, feks `{"draft", "unofficial", "official"}`. Så kan resultata gå til nett når de har status enten "unofficial" eller "official".
Oppdatering av dette feltet kan jo feks ligge i det samme registreringsbildet som målplassering, men må då gjelde for resultatet for det gitt racet samla.
```
class RaceResultStatus(Enum):
   """Valid vaules for a raceresult status."""
   DRAFT = 0
   UNOFFICIAL = 1
   OFFICIAL = 2

@dataclass
class RaceResult(DataClassJsonMixin):
    """Data class with details about a race-result."""

    id: str
    race_id: str
    timing_point: str
    no_of_contestants: int
    status: RaceResultEnum
    ranking_sequence: List[str]  # list of references to TimeEvent
```

**Comment by heming-langrenn** [comment]
Det høres ut som en bra plan med RaceResultStatus. Bør vi også ha en attributt på event nivå som sier om det er DRAFT eller UNOFFICIAL som skal være default? Det virker jo som at det er litt ulike preferanser her :-).

**Comment by stigbd** [comment]
Strengt tatt trenger ikkje et event, isolert sett, å ha ein slik status, så lenge eventet kun inneheld informasjon om at løper har passert et timing-point. Men sidan våre eventer inneheld anna informasjon også, feks rank, bør ikkje disse publiseres før race-result er UNOFFICIAL. 
Eg ville foreslått at eventene "arver" status til race-result, og at eventet sjølv ikkje trenger dette attributtet.

**Comment by heming-langrenn** [comment]
Fungerer med tidtakersiden nå - det gjenstår å reflektere i visning av live resultater og heat resultater. Foreslår at i første omgang vises alt, men de uoffisielle er i grå farge.
